var topBar={
    src:"./1.jpg",
    style:"width:100vw;max-height:30vh;",
};
var data=[
    {
        name:"中文",
        items:[
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'<h1>文章标题</h1><p>h1</p>'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'hhh2'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'hhh2'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'hhh2'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'hhh2'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'<h1>文章标题</h1><p>h1</p>'},
        ]
    },
    {
        name:"传统",
        items:[
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'传统'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'传统'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'传统'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'传统'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'传统'},
        ]
    },
    {
        name:"文化",
        items:[
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
        ],
    },
    {
        name:"文化2",
        items:[
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
        ],
    },
];
