var topBar={
    src:"./1.jpg",
    style:"width:100vw;max-height:30vh;",
};
var data=[
    {
        name:"中文",
        items:[
            {
                url:"http://mp.weixin.qq.com/s?__biz=MzIwMTAyNTQwOA==&mid=406573036&idx=1&sn=677fafd6e6a0c0cf412813f1ed8dd8a8#rd",
                img:"https://mmbiz.qlogo.cn/mmbiz/MIC3esuvOLID9p3icYaBZNFXLcwibNv0ttibpibbYicLPicoLMTSlqhicdNwjvVBTdPCic4FarsUYYYtzBcAicPRUMPW8FQ/0?wx_fmt=jpeg",
                tip:'增肌误区：为何你练的肌肉没效果？'
            },
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'hhh2'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'hhh2'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'hhh2'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'hhh2'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'<h1>文章标题</h1><p>h1</p>'},
        ]
    },
    {
        name:"传统",
        items:[
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'传统'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'传统'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'传统'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'传统'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'传统'},
        ]
    },
    {
        name:"文化",
        items:[
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
        ],
    },
    {
        name:"文化2",
        items:[
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
            {url:"http://www.qq.com",img:"https://www.baidu.com/img/bd_logo1.png",tip:'文化'},
        ],
    },
];
